### ISSUE TITLE
Can't seem to build the file

### ISSUE THREAD

**Issue by Cyb3rN3rd777** [EvilBytecode/PPID-Spoofing#1]
Hello, 

Thanks for sharing this tool. 

I have a question, i tried to build the file but it doesn't seem to work. 
Can you provide a little guide on how to build it or run it ?
![screen](https://github.com/EvilBytecode/PPID-Spoofing/assets/144471817/55bdde60-be7e-4813-a354-06677849d4ce)

Thanks,

**Comment by EvilBytecode** [comment]
Ehh, lemme see if i can build lol.

**Comment by EvilBytecode** [comment]
![image](https://github.com/EvilBytecode/PPID-Spoofing/assets/151552809/c849093a-79b9-43aa-90e3-0b2d4e9003f3)
Ye, issue on your side probs, make sure you have gcc since it uses C inside Go aka cgo.

**Comment by Cyb3rN3rd777** [comment]
well god damn! nice ill check that out, thank you
